#undef PPDHasGainIn
#undef PPDHasHQ
#undef PPDHasEditor
#undef PPDEqualLoudnessMix
#undef PPDFPSMeters
#undef PPDFPSKnobs
#undef PPDMetersUseRMS
#undef PPD_GainIn_Min
#undef PPD_GainIn_Max
#undef PPD_GainOut_Min
#undef PPD_GainOut_Max
#undef PPDHasUnityGain
#undef PPD_UnityGainDefault
#undef PPDFPSValueBubble
#undef PPDValueBubbleVisibleTimeMs
#undef PPDFPSTextEditor
#undef PPD_DebugFormularParser
#undef PPDHasPatchBrowser
#undef PPDPitchShifterSizeMs
#undef PPDPitchShifterNumVoices
#undef PPDHasStereoConfig
#undef PPDHasPolarity
#undef PPDEditorWidth
#undef PPDEditorHeight